apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1000

      initContainers:
      - name: fix-permissions
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          mkdir -p /var/www/html/storage/logs
          mkdir -p /var/www/html/storage/framework/sessions
          mkdir -p /var/www/html/storage/framework/views
          mkdir -p /var/www/html/storage/framework/cache
          mkdir -p /var/www/html/bootstrap/cache

          # পারমিশন ফিক্স করা
          chown -R 1000:1000 /var/www/html/storage /var/www/html/bootstrap/cache
          chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache
        volumeMounts:
        - name: storage-volume
          mountPath: /var/www/html/storage

      containers:
      - name: laravel
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        - secretRef:
            name: {{ .Release.Name }}-secret
        volumeMounts:
        - name: storage-volume
          mountPath: /var/www/html/storage
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 30
          periodSeconds: 10

      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
